In [1]:
# Importing libraries.

import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt  
%matplotlib inline

In [2]:
avg_scores = pd.read_csv('input_data/naep.csv')
poverty_income = pd.read_csv('input_data/poverty_income.csv')
unemploy_crime = pd.read_csv('input_data/unemployment_crime.csv')

In [3]:
unemploy_crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 459 entries, 0 to 458
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   year                 459 non-null    int64  
 1   state                459 non-null    object 
 2   unemployment_rate    459 non-null    float64
 3   violent_crime_rate   459 non-null    float64
 4   property_crime_rate  459 non-null    float64
dtypes: float64(3), int64(1), object(1)
memory usage: 18.1+ KB


In [4]:
merged_df = pd.merge(avg_scores, poverty_income, how = 'left' , left_on =['state', 'year'], right_on=['state', 'year'])
merged_df = pd.merge(merged_df, unemploy_crime, how = 'left' , left_on =['state', 'year'], right_on=['state', 'year'])
merged_df

year          state   avg_score      subject  grade  poverty_percent  \
0     2019        Alabama  268.703899  Mathematics      8             15.6   
1     2019         Alaska  274.337801  Mathematics      8             10.2   
2     2019        Arizona  279.932022  Mathematics      8             13.5   
3     2019       Arkansas  274.363192  Mathematics      8             16.0   
4     2019     California  275.608909  Mathematics      8             11.8   
...    ...            ...         ...          ...    ...              ...   
1831  2003       Virginia  223.340359      Reading      4             10.0   
1832  2003     Washington  221.096695      Reading      4             11.0   
1833  2003  West Virginia  219.179525      Reading      4             16.3   
1834  2003      Wisconsin  220.833428      Reading      4              8.9   
1835  2003        Wyoming  222.075166      Reading      4             10.8   

      median_income  unemployment_rate  violent_crime_rate  \
0             51771                3.0              504.67   
1             77203                5.4              865.05   
2             62027                4.9              447.12   
3             49020                3.5              580.84   
4             80423                4.2              442.07   
...             ...                ...                 ...   
1831          50028                4.1              278.20   
1832          48185                7.4              346.94   
1833          32967                6.0              255.43   
1834          46538                5.7              221.11   
1835          41554                4.3              261.70   

      property_crime_rate  
0                 2622.80  
1                 2902.52  
2                 2435.98  
3                 2847.71  
4                 2335.78  
...                   ...  
1831              2721.54  
1832              4754.98  
1833              2339.02  
1834              2880.45  
1835              3315.60  

[1836 rows x 10 columns]

In [5]:
math_merged_df = merged_df.loc[(merged_df['subject'] == 'Mathematics')]
math_4_merged_df = math_merged_df.loc[(merged_df['grade'] == 4)]
math_4_merged_df

year          state   avg_score      subject  grade  poverty_percent  \
459  2019        Alabama  229.651002  Mathematics      4             15.6   
460  2019         Alaska  232.307479  Mathematics      4             10.2   
461  2019        Arizona  237.610210  Mathematics      4             13.5   
462  2019       Arkansas  233.252134  Mathematics      4             16.0   
463  2019     California  234.721976  Mathematics      4             11.8   
..    ...            ...         ...          ...    ...              ...   
913  2003       Virginia  239.203089  Mathematics      4             10.0   
914  2003     Washington  238.292840  Mathematics      4             11.0   
915  2003  West Virginia  230.767749  Mathematics      4             16.3   
916  2003      Wisconsin  236.755414  Mathematics      4              8.9   
917  2003        Wyoming  241.085701  Mathematics      4             10.8   

     median_income  unemployment_rate  violent_crime_rate  property_crime_rate  
459          51771                3.0              504.67              2622.80  
460          77203                5.4              865.05              2902.52  
461          62027                4.9              447.12              2435.98  
462          49020                3.5              580.84              2847.71  
463          80423                4.2              442.07              2335.78  
..             ...                ...                 ...                  ...  
913          50028                4.1              278.20              2721.54  
914          48185                7.4              346.94              4754.98  
915          32967                6.0              255.43              2339.02  
916          46538                5.7              221.11              2880.45  
917          41554                4.3              261.70              3315.60  

[459 rows x 10 columns]

In [6]:
math_4_merged_df = math_4_merged_df.drop(columns = 'year')
math_4_merged_df = math_4_merged_df.drop(columns = 'state')
math_4_merged_df = math_4_merged_df.drop(columns = 'subject')
math_4_merged_df = math_4_merged_df.drop(columns = 'grade')
math_4_merged_df = math_4_merged_df.drop(columns = 'violent_crime_rate')
math_4_merged_df = math_4_merged_df.drop(columns = 'property_crime_rate')
math_4_merged_df

avg_score  poverty_percent  median_income  unemployment_rate
459  229.651002             15.6          51771                3.0
460  232.307479             10.2          77203                5.4
461  237.610210             13.5          62027                4.9
462  233.252134             16.0          49020                3.5
463  234.721976             11.8          80423                4.2
..          ...              ...            ...                ...
913  239.203089             10.0          50028                4.1
914  238.292840             11.0          48185                7.4
915  230.767749             16.3          32967                6.0
916  236.755414              8.9          46538                5.7
917  241.085701             10.8          41554                4.3

[459 rows x 4 columns]

In [7]:
math_4_merged_df.isnull().sum()

avg_score            0
poverty_percent      0
median_income        0
unemployment_rate    0
dtype: int64

In [8]:
math_4_merged_df = math_4_merged_df.dropna()

In [9]:
math_4_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 459 entries, 459 to 917
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   avg_score          459 non-null    float64
 1   poverty_percent    459 non-null    float64
 2   median_income      459 non-null    int64  
 3   unemployment_rate  459 non-null    float64
dtypes: float64(3), int64(1)
memory usage: 17.9 KB


In [10]:
# Divide the Data into Attributes & Labels

x = math_4_merged_df.drop(columns = 'avg_score') 
y = math_4_merged_df['avg_score'].values
print(y)

[229.6510022 232.3074785 237.6102104 233.2521342 234.7219756 241.8655865
 243.2595018 239.3196595 234.6351761 245.9576065 237.6484542 238.5673371
 241.8987352 237.3973218 244.8831298 240.6887381 239.4397937 239.310713
 231.2974132 240.7575903 238.5624885 247.31944   236.1515849 248.4095328
 240.7068903 238.4101906 241.1131899 243.770986  235.6262726 244.5591963
 245.9315987 231.1103167 236.7307072 241.4081364 242.9283908 241.1404735
 237.1954249 236.3490312 243.9368521 239.3440462 236.7545226 241.2962777
 239.6985041 243.6165426 243.7890458 238.8998974 246.8894795 239.5108175
 231.4961373 241.6712452 245.8434399 232.1706877 230.4562776 234.4357882
 233.8481437 232.262941  240.6950166 239.2376509 236.1275617 231.3204621
 246.3676958 236.383603  237.9197687 239.9675141 238.1189474 246.5137501
 243.1074844 241.2128046 239.1782574 228.9717454 239.8989945 240.6012773
 249.1026739 235.5554725 248.8043026 234.694193  239.5022892 240.7216345
 245.5906746 231.6851622 245.3198386 247.8552312 229

In [11]:
# Split Data into Training & Test Sets.

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 42)

In [12]:
# Train the Algorithm.

from sklearn.linear_model import LinearRegression  
regression = LinearRegression()  
regression.fit(x_train, y_train) 

LinearRegression()

In [13]:
# Predict Scores for the Model.

print(x_test) 
y_pred = regression.predict(x_test)


     poverty_percent  median_income  unemployment_rate
583             15.7          51063                5.4
489              9.1          85786                3.4
658             11.7          62745                5.7
897              8.9          56356                5.8
613             10.1          70058                7.0
..               ...            ...                ...
576             12.1          54843                3.8
693             10.4          67574                9.3
697             12.0          52135                3.5
563             17.4          51473                6.1
805             15.1          43508                5.7

[115 rows x 3 columns]


In [14]:
# Compare Actual Data vs Predicted Data

score_vs_factors = pd.DataFrame({"Actual Scores": y_test, "Predicted Scores": y_pred})
score_vs_factors

Actual Scores  Predicted Scores
0       235.728894        236.732262
1       245.931599        243.908692
2       246.177457        241.323866
3       238.776541        243.985802
4       236.122004        243.698254
..             ...               ...
110     243.339912        239.923121
111     248.004163        244.173733
112     245.156416        239.816720
113     237.611755        235.281463
114     237.107412        237.190902

[115 rows x 2 columns]

In [15]:
pd.DataFrame(np.c_[x_test,y_test,y_pred], columns=["Poverty Percentage","Median Income", "Unemployment Rate","Actual Scores","Predicted Scores"])

Poverty Percentage  Median Income  Unemployment Rate  Actual Scores  \
0                  15.7        51063.0                5.4     235.728894   
1                   9.1        85786.0                3.4     245.931599   
2                  11.7        62745.0                5.7     246.177457   
3                   8.9        56356.0                5.8     238.776541   
4                  10.1        70058.0                7.0     236.122004   
..                  ...            ...                ...            ...   
110                12.1        54843.0                3.8     243.339912   
111                10.4        67574.0                9.3     248.004163   
112                12.0        52135.0                3.5     245.156416   
113                17.4        51473.0                6.1     237.611755   
114                15.1        43508.0                5.7     237.107412   

     Predicted Scores  
0          236.732262  
1          243.908692  
2          241.323866  
3          243.985802  
4          243.698254  
..                ...  
110        239.923121  
111        244.173733  
112        239.816720  
113        235.281463  
114        237.190902  

[115 rows x 5 columns]

In [16]:
# Test with Custom Data.

input = [[15.6, 51771, 3.0]]
prediction = regression.predict(input)
print("Predicted Score = {}".format(prediction[0]))

Predicted Score = 235.95334772083837


In [17]:
# Evaluate Performance of Algorithm.

from sklearn import metrics  
print('Mean Absolute Error:', 
      metrics.mean_absolute_error(y_test, y_pred))

Mean Absolute Error: 4.305307709052325


In [18]:
regression.score(x_train, y_train)

0.2720990058660867

In [19]:
regression.score(x_test, y_test)

0.1956428996107804

In [20]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(x_train)
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [21]:
regression = LinearRegression()  
regression.fit(x_train_scaled, y_train)

LinearRegression()

In [22]:
regression.score(x_train_scaled, y_train)

0.27209900586608704

In [23]:
regression.score(x_test_scaled, y_test)

0.1956428996107804

In [24]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_pred, y_test)

32.62079516968048

In [25]:
math_4_merged_df['avg_score'].describe()

count    459.000000
mean     239.010713
std        6.247868
min      204.919850
25%      235.707934
50%      239.760481
75%      243.216642
max      253.420961
Name: avg_score, dtype: float64

In [26]:
bins = [0, 214.9, 230.9, 245.9, 260]
group_names = [0, 1, 2, 3]
math_4_merged_df['new_col'] = pd.cut(math_4_merged_df['avg_score'],bins, labels=group_names, include_lowest=True)

In [27]:
math_4_merged_df

avg_score  poverty_percent  median_income  unemployment_rate new_col
459  229.651002             15.6          51771                3.0       1
460  232.307479             10.2          77203                5.4       2
461  237.610210             13.5          62027                4.9       2
462  233.252134             16.0          49020                3.5       2
463  234.721976             11.8          80423                4.2       2
..          ...              ...            ...                ...     ...
913  239.203089             10.0          50028                4.1       2
914  238.292840             11.0          48185                7.4       2
915  230.767749             16.3          32967                6.0       1
916  236.755414              8.9          46538                5.7       2
917  241.085701             10.8          41554                4.3       2

[459 rows x 5 columns]

In [28]:
math_4_merged_df = math_4_merged_df.drop(columns = 'avg_score')
math_4_merged_df

poverty_percent  median_income  unemployment_rate new_col
459             15.6          51771                3.0       1
460             10.2          77203                5.4       2
461             13.5          62027                4.9       2
462             16.0          49020                3.5       2
463             11.8          80423                4.2       2
..               ...            ...                ...     ...
913             10.0          50028                4.1       2
914             11.0          48185                7.4       2
915             16.3          32967                6.0       1
916              8.9          46538                5.7       2
917             10.8          41554                4.3       2

[459 rows x 4 columns]

In [29]:
x = math_4_merged_df.drop(columns = 'new_col').values
y = math_4_merged_df['new_col'].values

In [30]:
import tensorflow as tf

y = tf.keras.utils.to_categorical(y)
x_train, x_test, y_train, y_test = train_test_split(x,y, random_state = 78)
print(y)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]


In [31]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
x_scaler = scaler.fit(x_train)

# Scale the data
x_train_scaled = x_scaler.transform(x_train)
x_test_scaled = x_scaler.transform(x_test)

In [32]:
import tensorflow as tf

input_features = len(x_train_scaled[0])
hidden_layer1 = 50
hidden_layer2 = 35
# hidden_layer3 = 10

nn = tf.keras.models.Sequential()

nn.add(tf.keras.layers.Dense(units = hidden_layer1, input_dim = input_features, activation = 'relu'))

nn.add(tf.keras.layers.Dense(units = hidden_layer2, activation = 'relu'))

# nn.add(tf.keras.layers.Dense(units = hidden_layer3, activation = 'tanh'))

nn.add(tf.keras.layers.Dense(units = 4, activation = 'softmax'))

nn.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 50)                200       
                                                                 
 dense_1 (Dense)             (None, 35)                1785      
                                                                 
 dense_2 (Dense)             (None, 4)                 144       
                                                                 
Total params: 2,129
Trainable params: 2,129
Non-trainable params: 0
_________________________________________________________________


In [33]:
nn.compile(loss="categorical_crossentropy", optimizer= "adam", metrics=['accuracy'])

In [34]:
fit_model = nn.fit(x_train_scaled, y_train, epochs=100)

Epoch 1/100
11/11 [==============================] - 0s 1ms/step - loss: 1.3089 - accuracy: 0.3953
Epoch 2/100
11/11 [==============================] - 0s 1ms/step - loss: 1.1065 - accuracy: 0.7878
Epoch 3/100
11/11 [==============================] - 0s 1ms/step - loss: 0.9587 - accuracy: 0.7907
Epoch 4/100
11/11 [==============================] - 0s 1ms/step - loss: 0.8562 - accuracy: 0.7907
Epoch 5/100
11/11 [==============================] - 0s 1ms/step - loss: 0.7869 - accuracy: 0.7907
Epoch 6/100
11/11 [==============================] - 0s 1ms/step - loss: 0.7363 - accuracy: 0.7907
Epoch 7/100
11/11 [==============================] - 0s 1ms/step - loss: 0.6969 - accuracy: 0.7907
Epoch 8/100
11/11 [==============================] - 0s 1ms/step - loss: 0.6630 - accuracy: 0.7907
Epoch 9/100
11/11 [==============================] - 0s 1ms/step - loss: 0.6386 - accuracy: 0.7907
Epoch 10/100
11/11 [==============================] - 0s 2ms/step - loss: 0.6191 - accuracy: 0.7907
Epoch 11/

Epoch 83/100
11/11 [==============================] - 0s 1ms/step - loss: 0.4763 - accuracy: 0.8140
Epoch 84/100
11/11 [==============================] - 0s 1ms/step - loss: 0.4793 - accuracy: 0.8256
Epoch 85/100
11/11 [==============================] - 0s 1ms/step - loss: 0.4722 - accuracy: 0.8256
Epoch 86/100
11/11 [==============================] - 0s 1ms/step - loss: 0.4748 - accuracy: 0.8227
Epoch 87/100
11/11 [==============================] - 0s 1ms/step - loss: 0.4722 - accuracy: 0.8198
Epoch 88/100
11/11 [==============================] - 0s 1ms/step - loss: 0.4718 - accuracy: 0.8256
Epoch 89/100
11/11 [==============================] - 0s 2ms/step - loss: 0.4727 - accuracy: 0.8227
Epoch 90/100
11/11 [==============================] - 0s 4ms/step - loss: 0.4709 - accuracy: 0.8227
Epoch 91/100
11/11 [==============================] - 0s 1ms/step - loss: 0.4704 - accuracy: 0.8110
Epoch 92/100
11/11 [==============================] - 0s 2ms/step - loss: 0.4690 - accuracy: 0.8256


In [35]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(x_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

4/4 - 0s - loss: 0.5189 - accuracy: 0.8174 - 174ms/epoch - 44ms/step
Loss: 0.5188641548156738, Accuracy: 0.8173912763595581


In [36]:
input = [[15.6, 51771, 3.0]]
predictions = nn.predict(input)
print(predictions)


[[0. 0. 1. 0.]]


In [37]:
nn.save('grade_4_math_model.h5')